### ISSUE TITLE
what folks were requesting of npm's search

### ISSUE THREAD

**Issue by dkebler** [npms-io/npms-www#135]
Just forwarding a link to a issue/request made long ago at about npm's website which never went anywhere.

Very happy to see someone else has finally picked up the ball and run with this major issue...thx!

https://github.com/npm/www/issues/6

the score is a good idea but additional filtering, sorting and/or ability for visitor to tweak the scoring algorithm would be a plus.

**Comment by satazor** [comment]
Hey @dkebler 

We have a good number of filters in place, you may find them here: https://api-docs.npms.io/#api-Search-ExecuteSearchQuery. Let me know if you have a specific filter requirement not present there.

Regarding additional sorting features, could you look at my comment at https://github.com/npms-io/npms-www/issues/133? We got that almost done, we just need feedback to see if it's good enough.
We won't allow sorting for a specific metric because that goes against how `npms` scores packages. Instead, the sorting options offered in that branch are based on `quality`, `popularity` and `maintenance` weights.

**Comment by dkebler** [comment]
on npmjs.org After thinking I found a good package I have to jump to github repo and take a look at the latest commit.  Packages not being maintained (say no commits in last x months) or with a bunch of unclosed issues are not worth my time. Is that what your maintenance score tracks?   How to find tune that?  Seems I saw something in the api for weights?  

It's pretty easy to find popular/used packages (which tend to be maintained) but what has been hard is to find are high quality packages that may not have a ton of use yet.   

I suppose the "npms score" is a sorting but if the score is the only way to query without some override or filter then not as useful.  How about a query like this  (keywords: promise queue, sort by: your nmps score, filter by: first commit in the last year, last commit in last 2 months, github 5<stars<100) might find me  decent repos related to promise queues that probably use ES6 syntax.   Such a query in the past would have yielded nothing but as npm db has grown some gems.

In general It seems as though github has some of the important stats for a package so does npms only access the npm db?  or the github db for the corresponding package repo as well?

I understand that via the api or the website search box one can tweak things "manually"  but down the road the webapp gui should give the visitor a little help with that.   Not sure I have time to memorize another Api :).   I do have several github search "templates" saved as bookmarks for searching github but kinda wish that I could just do some clicking for more advanced search or tweaking your algorithm.  
Looks like you are using a rest api for the search so at least I can bookmark them and come back and change my keywords.

So some input...but really Thx for you time and efforts.  Even as it is it's way better the npms.org web.

**Comment by satazor** [comment]
@dkebler I definitely agree with you that's why we want to offer additional sorting features. The attached screenshot shows an upcoming feature that will allow to tweak the weights, so that you can tweak `quality` and `maintenance` over `popularity`. 

This answers most of your points in a way that is simple and (hopefully) intuitive. What do you think?

Thanks for showing up and give some input which is always nice!

![screen shot 2016-11-12 at 13 13 22](https://cloud.githubusercontent.com/assets/1017236/21283011/66b2bd66-c3f3-11e6-824a-769259950416.png)

**Comment by dkebler** [comment]
Yea that's the idea.  perfect.  

more suggestions then.

To expand on that if user clicks on a parameter (e.g. Quality) a modal could open that one would allow tweaking the  algorithm for that parameter (whatever has not been hard coded).  Might as well link/display relevant documentation on how that parameter is calculated (way important)

Could also include an "advanced" link/dialog where you could put in post weight query additional filters like I mentioned (e.g. first commit in last year).

So little by little the "front ender"  could add more gui enabled access to the API as it grows.

Down the road  I'd add the ability to name/save/recall search settings.  It would allow user to bring up some useful past advanced searches and for example swap the keywords (that's what I so manually at github now).  I wouldn't set up any internal user/storage system just use their github account (using a token if need be) and save the searches to a gist(s) or maybe a repo.  For example there's an Atom settings sync package that just does that.  Allows you to sync settings between Atom instances on different machines by writing and reading them to/from a gist.  Personally I'd write them out as mongodb style collection of search objects in their format of choice: json,cson,yaml,toml,honey... (mine is cson).   Then it's way easy for a user to manually copy/tweak etc and add comments to the file.  I'm doing all my project settings that way now.    There are packages that will load or "require" any of those simply based on extension.   So if you don't already have a search "object" in your code probably good time to think about all the keys it might contain.  In a collection format it's super easy to use something like Lowdb https://github.com/typicode/lowdb to manipulate the collection which is what I do.
