### ISSUE TITLE
Link to package details page on yarnpkg.com

### ISSUE THREAD

**Issue by AndrewPrifer** [npms-io/npms-www#206]
The yarnpkg website recently got a search feature and package details page. The search is kinda meh compared to npms, but the package details page is really awesome ([example](https://yarnpkg.com/en/package/validator)) and far superior to the one on npmjs.com. Would it be a good idea to link to that as well from the results? What do you think?

**Comment by satazor** [comment]
I think npmjs will be rolling out an improved package details page soon. Perhaps @bcoe could give some insight.

**Comment by isaacs** [comment]
It's true, we are currently working on some significant changes to our website.  An improved package details page will be part of that, with ongoing improvements planned throughout 2018.  (Presumably we'll keep improving things in 2019 and beyond, just don't have specific plans for that yet :)

@andrewpeterprifer I'm curious about what specifically you see as "far superior"?  I'm not trying to be defensive, as I know that npmjs.com's package details page has some significant shortcomings, I just want to make sure that we address the problems you're seeing.  (Happy to take this offline, as well, since it's not 100% relevant to npms.io, but it does seem somewhat related to the question of where they link.)

**Comment by AndrewPrifer** [comment]
Thanks for joining the conversation @isaacs. My comment might have been overly enthusiastic, I meant no offense. ;)

What I really, really like about yarnpkg's details page is the following, more or less in this order:

1. Changelog
2. Github activity (number of commits in last 3 months, latest commit, number of stars) I think these are really good indicators of package maintenance. Yes, npmjs shows the number of open issues, but that also varies with the size and popularity of the project which makes it hard to draw quick conclusions.
3. List of versions by date. Why? Because it gives me a quick glance at the maturity of the package, frequency of updates and frequency of breaking changes.
4. Link to package.json
5. Link to project website

I also feel that the overall structure and presentation of information is better.
